name: final_project
description: "Mobile_Programming-Final_Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.64.0
  device_preview: 1.2.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  currency_picker: ^2.0.21
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  provider: ^6.1.2
  cloud_firestore: ^5.5.0
  intl: ^0.19.0
  currency_textfield: ^4.14.1
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/home/
    - images/modal/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
