// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlH3SED38xfRNEuc2dBPsmKEHwN9SQR5A',
    appId: '1:156154230572:web:6baa147bee07f27ea99e89',
    messagingSenderId: '156154230572',
    projectId: 'expenser-7223d',
    authDomain: 'expenser-7223d.firebaseapp.com',
    storageBucket: 'expenser-7223d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDXxO929wzcma_kJyAPJIu8aKPzV_cf30',
    appId: '1:156154230572:android:c8784e788e70b835a99e89',
    messagingSenderId: '156154230572',
    projectId: 'expenser-7223d',
    storageBucket: 'expenser-7223d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8SpyIIzYQO3DET90S024OE5Mw3H9NPVA',
    appId: '1:156154230572:ios:a489c3e919da1c5da99e89',
    messagingSenderId: '156154230572',
    projectId: 'expenser-7223d',
    storageBucket: 'expenser-7223d.firebasestorage.app',
    iosBundleId: 'org.expenser.dev.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8SpyIIzYQO3DET90S024OE5Mw3H9NPVA',
    appId: '1:156154230572:ios:a489c3e919da1c5da99e89',
    messagingSenderId: '156154230572',
    projectId: 'expenser-7223d',
    storageBucket: 'expenser-7223d.firebasestorage.app',
    iosBundleId: 'org.expenser.dev.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlH3SED38xfRNEuc2dBPsmKEHwN9SQR5A',
    appId: '1:156154230572:web:fb04cf1474264873a99e89',
    messagingSenderId: '156154230572',
    projectId: 'expenser-7223d',
    authDomain: 'expenser-7223d.firebaseapp.com',
    storageBucket: 'expenser-7223d.firebasestorage.app',
  );
}
